clc;clear all;close all;
rgb_img=imread('E:\3-2\ICE-3207 DISP\ICE-3208 Sessional\Exm\\JWST.jpg');
rgb_img=im2double(rgb_img);
subplot(241);imshow(rgb_img);title('Original RGB image');
R=rgb_img; R(:,:,2)=0; R(:,:,3)=0;
G=rgb_img; G(:,:,1)=0; G(:,:,3)=0;
B=rgb_img; B(:,:,1)=0; B(:,:,2)=0;
subplot(242);imshow(R);title('Red component');
subplot(243);imshow(G);title('Green component');
subplot(244);imshow(B);title('Blue component');
subplot(245);imshow(rgb_img);title('RGB image');
hsi_img=rgb2hsv(rgb_img);
H=hsi_img; H(:,:,2)=0; H(:,:,3)=0;
S=hsi_img; S(:,:,1)=0; S(:,:,3)=0;
I=hsi_img; I(:,:,1)=0; I(:,:,2)=0;
subplot(246);imshow(H);title('Hue component');
subplot(247);imshow(S);title('Saturation');
subplot(248);imshow(I);title('Intensity component');